name: Build Jar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-jar
        path: build/libs/*.jar
